config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  post '/signin', to: 'users#signin'
  get '/suggestions', to: 'articles#suggestions'
  
  resources :users, only: [:new, :show, :update, :index, :create, :edit] do
    resources :articles, only: [:new, :show, :update, :edit, :create, :index] 
  end

  resource :votes, only: [:new, :edit] 

  resources :articles, only: [:new, :show, :update, :edit, :create, :index]

  get '/search', to: 'articles#search'

  resources :categories, only: [:new, :edit, :index, :create, :update] do 
    resources :articles, only: [:new, :show, :update, :edit, :create, :index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :username, presence: true

  has_many :articles, foreign_key: :author_id, source: :articles
  has_many :votes

  def self.myself?(user_id, logged_user)
    @user = User.find(user_id)
    return false unless @user.id != logged_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_loggedin?, only: %i[index show update]
  before_action :find_user, only: %i[show update edit]

  def new
    @user = User.new
  end

  def index
    @users = User.all.order(:name)
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def edit
    return if Article.mine?(params[:id], session[:current_user]['id'])

    redirect_to root_path, notice: 'Current user is not allowed to edit this user'
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'Category successfully updated'
    else
      redirect_to edit_user_path(@user), notice: 'An error ocurred while updating this user'
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user] = @user
      redirect_to user_path(@user), notice: 'User successfully created'
    else
      render new_user_path, notice: 'User was not created'
    end
  end

  def signin
    @user = User.find_by(username: params[:username])
    if !@user.nil?
      session[:current_user] = @user
      redirect_to root_path
    else
      redirect_to login_path, notice: 'Username not found'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end

  def find_user
    if params[:id].nil?
      flash[:notice] = 'Invalid user'
    else
      @user = User.find(params[:id])
    end
  end

  def user_loggedin?
    redirect_to login_path if session[:current_user].nil?
  end

  def signin_params
    params.require(:user).permit(:username)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def display_errors(user)
    return unless user.errors.any?

    user.errors.full_messages.collect do |message|
      content_tag(:div, class: 'bg-dark text-white d-flex justify-content-center font-weight-bold') do
        message
      end
    end.join.html_safe
  end

  def logged_in?
    return false if session[:current_user].nil?

    true
  end

  def edit_user?(user)
    if !session[:current_user].nil? && session[:current_user]['id'] == user.id
      return link_to 'Edit', edit_user_path(user).html_safe
    end

    flash[:notice] = 'User not allowed edit'
  end
end

app/views/users/_article.html.erb
<div class="card w-50 mx-auto mt-5">
  <div class="card-header">
    <h1><%= article.title %></h1>
    <span class = 'text-dark font-weigh-bold'>Number of votes: <%= article.votes.count %></span>
    <%= image_tag  article.photo, class: 'article-image' %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= article.text %></p>
    <%= edit_article?(article) %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="card w-50 mx-auto mt-5">
  <div class="card-header">
    <h1><%= user.name %></h1>
  </div>
  <div class="card-body">
    <p class="card-text"><%= user.username %></p>
    <%= edit_user?(user) %>
  </div>
</div>

app/views/users/_userform.html.erb
<div class = 'form w-50 mx-auto mt-5 bg-light p-3 rounded'>
  <h1 class = 'd-flex justify-content-center'>Create a user</h1>
  <%= form_for @user do |f| %>
    <div class = 'errors'>
      <%= display_errors(@user) %>
    </div>
    <%= f.text_field :name, class: 'form-control mt-2', placeHolder: 'Name' %>
    <%= f.text_field :username, class: 'form-control mt-2', placeHolder: 'Username' %>
    <%= f.submit class: 'btn btn-lg btn-submit text-dark btn-block mt-4'  %>
  <% end %>
</div>

app/views/users/articles.html.erb
<% @articles.each do |article| %>
  <%= render 'users/article', article: article %>
<% end %>

app/views/users/edit.html.erb
<%= render 'userform' %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= render 'user', :user => user %>
<% end %>

app/views/users/login.html.erb
<div class = 'form w-50 mx-auto mt-5 bg-light p-3 rounded'>
   <%= form_tag '/signin' do %>
      <h1 class = 'd-flex justify-content-center'>Login</h1>
      <%= text_field_tag(:username, '', class: 'form-control', placeHolder: 'Username') %>
      <%= submit_tag "Enter", class: 'btn btn-lg btn-submit text-dark btn-block mt-4'%>
   <%end%>
</div>

app/views/users/new.html.erb
<%= render 'userform' %>

app/views/users/show.html.erb
<%= render 'user', user: @user %>
<div class = 'p-3 w-50 bg-white mx-auto'><%= link_to  "Back to all users", users_path %></div>
<div class = 'p-3 w-50 bg-white mx-auto'>
  <%= link_to  "All categories", categories_path %>
</div>
<div class = 'p-3 w-50 bg-white mx-auto'>
  <%= link_to  "Create a category", new_category_path %>
</div>
<div class = 'p-3 w-50 bg-white mx-auto'><%= link_to  "Create an article", new_article_path %></div>
<div class = 'p-3 w-50 bg-white mx-auto'>
  <%= link_to  "My articles", user_articles_path(session[:current_user]['id']) %>
</div>
<div class = 'p-3 w-50 bg-white mx-auto'>
  <%= link_to  "Article suggestions", suggestions_path %>
</div>