config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  post '/signin', to: 'users#signin'
  get '/suggestions', to: 'articles#suggestions'
  
  resources :users, only: [:new, :show, :update, :index, :create, :edit] do
    resources :articles, only: [:new, :show, :update, :edit, :create, :index] 
  end

  resource :votes, only: [:new, :edit] 

  resources :articles, only: [:new, :show, :update, :edit, :create, :index]

  get '/search', to: 'articles#search'

  resources :categories, only: [:new, :edit, :index, :create, :update] do 
    resources :articles, only: [:new, :show, :update, :edit, :create, :index]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { mininum: 2, maximum: 20 }
  validates :priority, presence: true, numericality: { only_integer: true }

  has_many :article_categories
  has_many :articles, through: :article_categories, source: :article

  scope :priority_order, -> { order(:priority) }

  def most_recent_article
    articles.most_recents.limit(1)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[edit update]

  def index
    @categories = Category.all.order(:priority)
  end

  def show; end

  def new
    @category = Category.new
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'User successfully updated'
    else
      redirect_to edit_category_path(@category), notice: 'An error ocurred while updating this user'
    end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to root_path, notice: 'Category create successfully'
    else
      render new_category_path, notice: 'An error occurred'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def class_visible
    return 'd-flex' if logged_in?

    'd-none'
  end

  def edit_category?(category)
    return link_to 'Edit', edit_category_path(category) unless session[:current_user].nil?

    ''
  end

  def reversed?(count)
    count < 2 ? 'flex-row' : 'flex-row-reverse'
  end
end

app/views/categories/_article-category.html.erb
<div class = "d-flex <%= reversed?(count) %>">
  <div class = "p-2 w-50"
    style = "background: linear-gradient(to bottom, rgba(0,0,50,0), rgba(0,0,50,0), 
    rgba(0,0,50,0), rgba(0,0,50,.3), rgba(0,0,50,1)), 
    no-repeat center/auto  url('<%= url_for(article.photo) %>')">
  </div>
  <div class = "p-2 position-relative w-50"
  style = "background: linear-gradient(to bottom, rgba(0,0,50,0), rgba(0,0,50,0), 
    rgba(0,0,50,0), rgba(0,0,50,.3), rgba(0,0,50,1)), 
    repeat center/1%  
    url('https://images.tcdn.com.br/img/editor/up/670388/estilotexarabescolosangosestampa.jpg')">
    <ul class = 'd-flex list-unstyled'>
        <li class = 'ml-2 orange-link'>
          <%= link_to  category.name, category_articles_path(category.id), 
        class: 'font-weight-bold' %>
        </li>
    </ul>
    <div class = 'article-title-mini'>
      <%= render 'articles/article_buttons', article: article %>
      <h6 class = ' ml-2 mt-2 text-dark font-weight-bolder'>
        <%= article.title %>
      </h6>
    </div>
    <div>
      <p class = 'ml-2 category-article-text'><%= truncate(article.text, length: 200) %></p>
      <p class = 'd-flex flex-column flex-md-row ml-2 category-article-text  read-more position-absolute'>
        <span class = 'ml-2 author-name text-white font-weight-bolder'>
          Author: <%= article.author.name %>
        </span>
        <%= link_to  "Read more...", article_path(article.id),
        class: 'ml-2 article-link' %>
      </p>
    </div>
  </div>
</div>

app/views/categories/_categories.html.erb
<li class = 'orange-link px-1 category-list'><%= link_to  "HOME", root_path %></li>
<li class = "orange-link px-1 category-list">
  <%= link_to  "Write an article", new_article_path, class: "#{class_visible}" %>
</li>
<% Category.all.priority_order.each do |c| %>
  <li class='category-list'><%= link_to  c.name, 
  category_articles_path(c.id) %></li>
<% end %>

app/views/categories/_category.html.erb
<div class="card w-50 mx-auto mt-5">
  <div class="card-header">
    <h1><%= category.name %></h1>
  </div>
  <div class="card-body">
    <p class="card-text">Priority: <%= category.priority %></p>
    <%= edit_category?(category) %>
  </div>
</div>

app/views/categories/_categoryform.html.erb
<div class = 'form w-50 mx-auto mt-5 bg-light p-3 rounded'>
  <h1 class = 'd-flex justify-content-center'>Category</h1>
  <%= form_for @category do |f| %>
    <div class = 'errors'>
      <%= display_errors(@category) %>
    </div>
    <%= f.text_field :name, class: 'form-control mt-2', placeHolder: 'Name' %>
    <%= f.number_field :priority, class: 'form-control mt-2', placeHolder: 'Priority' %>
    <%= f.submit class: 'btn btn-lg btn-submit text-dark btn-block mt-4'  %>
  <% end %>
</div>

app/views/categories/_no-article-category.html.erb
<div class = "d-flex <%= reversed?(count) %>">
  <div class = "p-2 w-50"
    style = "background: linear-gradient(to bottom, rgba(0,0,50,0), rgba(0,0,50,0), 
    rgba(0,0,50,0), rgba(0,0,50,.3), rgba(0,0,50,1)), 
    no-repeat center/auto  url('<%= url_for(article.photo) %>')">
  </div>
  <div class = "p-2 position-relative w-50"
  style = "background: linear-gradient(to bottom, rgba(0,0,50,0), rgba(0,0,50,0), 
    rgba(0,0,50,0), rgba(0,0,50,.3), rgba(0,0,50,1)), 
    repeat center/1%  
    url('')">
    <ul class = 'd-flex list-unstyled'>
        <li class = 'ml-2 orange-link'>
          <%= link_to  category.name, category_articles_path(category.id), 
        class: 'font-weight-bold' %>
        </li>
    </ul>
    <div class = 'article-title-mini'>      
      <h6 class = ' ml-2 mt-2 text-dark font-weight-bolder'>      
      </h6>
    </div>
    <div>
      <p class = 'ml-2 category-article-text'></p>
      <p class = 'd-flex flex-column flex-md-row ml-2 category-article-text  read-more position-absolute'>
        <span class = 'ml-2 author-name text-white font-weight-bolder'>          
        </span>        
      </p>
    </div>
  </div>
</div>

app/views/categories/articles.html.erb
<section class = 'category-articles'>
  <%= articles_grid(@articles, @category) %>
</section>

app/views/categories/edit.html.erb
<%= render 'categoryform' %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <%= render 'category', :category => category %>
<% end %>

app/views/categories/new.html.erb
<%= render 'categoryform' %>